// Generated by scripts/buildBydel.js — do not edit by hand.
// Copenhagen neighbourhood groupings from DBU København.

export const bydel = {
  "Amager": [
    1537,
    1534,
    1544,
    1548,
    1553,
    1560,
    1566,
    1583
  ],
  "Brønshøj/Vanløse": [
    1543,
    1547,
    1599,
    1563,
    1588,
    1582
  ],
  "Frederiksberg": [
    1546,
    1549,
    1567
  ],
  "Gentofte": [
    3358,
    1533,
    1556,
    1565,
    1562,
    1579
  ],
  "Hvidovre": [
    1564
  ],
  "Indre by og Østerbro": [
    1532,
    1558,
    1581,
    1595
  ],
  "Nørrebro/Bispebjerg og Nordvest": [
    1542,
    1569,
    1987,
    1586
  ],
  "Rødovre": [
    1578
  ],
  "Vesterbro/Valby": [
    3742,
    1554,
    1561,
    1587,
    1590
  ]
};

export const lastUpdated = "2026-05-08";

/**
 * Get the bydel name for a given dbuId.
 * Returns null if the club is not in the Copenhagen bydel dataset.
 */
export function getBydel(dbuId) {
  for (const [name, ids] of Object.entries(bydel)) {
    if (ids.includes(dbuId)) return name;
  }
  return null;
}

/**
 * Get all dbuIds in a given bydel.
 */
export function getClubsByBydel(bydelName) {
  return bydel[bydelName] ?? [];
}

/**
 * List all bydel names.
 */
export function listBydele() {
  return Object.keys(bydel);
}
