// Generated by scripts/buildTeams.js — do not edit by hand.

export const teams = {
  "1532": {
    "name": "Boldklubben af 1893",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 35
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 2
      }
    ]
  },
  "1533": {
    "name": "Boldklubben 1903",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 23
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 2
      }
    ]
  },
  "1534": {
    "name": "Boldklubben 1908",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 15
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 3
      }
    ]
  },
  "1537": {
    "name": "AB Tårnby",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 13
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1542": {
    "name": "Bispebjerg Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1543": {
    "name": "Brønshøj Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 16
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1544": {
    "name": "Christianshavns Idræts Klub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 3
      }
    ]
  },
  "1546": {
    "name": "FA 2000",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 35
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 8
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 2
      }
    ]
  },
  "1547": {
    "name": "FC Damsø",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1548": {
    "name": "Dragør Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 9
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1549": {
    "name": "Frederiksberg Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 40
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 6
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1553": {
    "name": "Boldklubben Fremad Amager",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1554": {
    "name": "Boldklubben Fremad Valby",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 19
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      }
    ]
  },
  "1556": {
    "name": "Gentofte-Vangede Idrætsforening",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 4
      }
    ]
  },
  "1558": {
    "name": "Handelsstandens Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 28
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 3
      }
    ]
  },
  "1560": {
    "name": "Boldklubben Hekla",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1561": {
    "name": "Hellas",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1562": {
    "name": "Hellerup Idræts Klub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 14
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1563": {
    "name": "Husum Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 9
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1564": {
    "name": "Hvidovre Idrætsforening",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 2
      }
    ]
  },
  "1565": {
    "name": "Jægersborg Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1566": {
    "name": "Kastrup Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      }
    ]
  },
  "1567": {
    "name": "Kjøbenhavns Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 32
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U18",
        "birthYear": 2008,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 6
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 9
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 9
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 15
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 20
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 3
      }
    ]
  },
  "1569": {
    "name": "KFUMs Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1578": {
    "name": "Boldklubben Rødovre",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 14
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1579": {
    "name": "Skovshoved Idrætsforening",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 16
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1581": {
    "name": "Boldklubben Skjold",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 44
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 7
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1582": {
    "name": "Boldklubben Stefan",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1583": {
    "name": "Sundby Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 10
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 8
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 2
      }
    ]
  },
  "1586": {
    "name": "Boldklubben Union",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 25
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "piger",
        "count": 1
      }
    ]
  },
  "1587": {
    "name": "Valby Boldklub",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 17
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 6
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1588": {
    "name": "Vanløse Idræts Forening",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U5",
        "birthYear": 2021,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1590": {
    "name": "Boldklubben Vestia",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 12
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "1595": {
    "name": "Østerbro Idræts Forening",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 20
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 5
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 3
      }
    ]
  },
  "1599": {
    "name": "Boldklubben Fix",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 11
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U17",
        "birthYear": 2009,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 6
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 3
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U6",
        "birthYear": 2020,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U19",
        "birthYear": 2007,
        "gender": "drenge",
        "count": 2
      }
    ]
  },
  "1987": {
    "name": "Nørrebro United",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 12
      },
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "piger",
        "count": 9
      },
      {
        "ageGroup": "U16",
        "birthYear": 2010,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U15",
        "birthYear": 2011,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "drenge",
        "count": 2
      },
      {
        "ageGroup": "U14",
        "birthYear": 2012,
        "gender": "piger",
        "count": 2
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U13",
        "birthYear": 2013,
        "gender": "piger",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U11",
        "birthYear": 2015,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "drenge",
        "count": 8
      },
      {
        "ageGroup": "U10",
        "birthYear": 2016,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "drenge",
        "count": 5
      },
      {
        "ageGroup": "U9",
        "birthYear": 2017,
        "gender": "piger",
        "count": 3
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 4
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "piger",
        "count": 1
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "drenge",
        "count": 7
      },
      {
        "ageGroup": "U7",
        "birthYear": 2019,
        "gender": "piger",
        "count": 4
      }
    ]
  },
  "3358": {
    "name": "Aakanden GF",
    "lastUpdated": "2026-05-09",
    "teams": [
      {
        "ageGroup": "Senior",
        "birthYear": null,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U12",
        "birthYear": 2014,
        "gender": "drenge",
        "count": 1
      },
      {
        "ageGroup": "U8",
        "birthYear": 2018,
        "gender": "drenge",
        "count": 1
      }
    ]
  },
  "3742": {
    "name": "BK Frem (professional)",
    "lastUpdated": "2026-05-09",
    "teams": []
  }
};

/**
 * Get all teams for a club by dbuId.
 * Returns an array of { ageGroup, birthYear, gender, count } objects.
 */
export function getTeams(dbuId) {
  return teams[dbuId]?.teams ?? [];
}

/**
 * Get all clubs that have at least one team for a given age group.
 * @param {string} ageGroup — e.g. 'U10', 'U12', 'Senior'
 */
export function getClubsByAgeGroup(ageGroup) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t => t.ageGroup === ageGroup))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}

/**
 * Get all clubs that have teams of a given gender.
 * @param {string} gender — 'drenge' | 'piger'
 */
export function getClubsByGender(gender) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t => t.gender === gender))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}

/**
 * Get all clubs that have teams matching both age group and gender.
 */
export function findClubs({ ageGroup, gender } = {}) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t =>
      (!ageGroup || t.ageGroup === ageGroup) &&
      (!gender   || t.gender   === gender)
    ))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}
