/**
 * Reads bydel.json and writes bydel.js — the danish-football-clubs/bydel slice.
 *
 * Usage:
 *   node scripts/buildBydel.js
 */

import { readFileSync, writeFileSync } from 'fs';

const raw = JSON.parse(readFileSync('bydel.json', 'utf8'));

const output = `// Generated by scripts/buildBydel.js — do not edit by hand.
// Copenhagen neighbourhood groupings from DBU København.

export const bydel = ${JSON.stringify(raw.bydel, null, 2)};

export const lastUpdated = ${JSON.stringify(raw.lastUpdated)};

/**
 * Get the bydel name for a given dbuId.
 * Returns null if the club is not in the Copenhagen bydel dataset.
 */
export function getBydel(dbuId) {
  for (const [name, ids] of Object.entries(bydel)) {
    if (ids.includes(dbuId)) return name;
  }
  return null;
}

/**
 * Get all dbuIds in a given bydel.
 */
export function getClubsByBydel(bydelName) {
  return bydel[bydelName] ?? [];
}

/**
 * List all bydel names.
 */
export function listBydele() {
  return Object.keys(bydel);
}
`;

writeFileSync('bydel.js', output, 'utf8');
console.log(`✓ bydel.js written (${Object.keys(raw.bydel).length} bydele)`);
