/**
 * Reads teams.json and writes teams.js — the danish-football-clubs/teams slice.
 *
 * Usage:
 *   node scripts/buildTeams.js
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';

// Prefer the national dataset if it exists; fall back to the local teams.json.
const source = existsSync('teams-national.json') ? 'teams-national.json' : 'teams.json';
const raw    = JSON.parse(readFileSync(source, 'utf8'));
if (source === 'teams-national.json') console.log('Using teams-national.json (national dataset)');

const output = `// Generated by scripts/buildTeams.js — do not edit by hand.

export const teams = ${JSON.stringify(raw, null, 2)};

/**
 * Get all teams for a club by dbuId.
 * Returns an array of { ageGroup, birthYear, gender, count } objects.
 */
export function getTeams(dbuId) {
  return teams[dbuId]?.teams ?? [];
}

/**
 * Get all clubs that have at least one team for a given age group.
 * @param {string} ageGroup — e.g. 'U10', 'U12', 'Senior'
 */
export function getClubsByAgeGroup(ageGroup) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t => t.ageGroup === ageGroup))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}

/**
 * Get all clubs that have teams of a given gender.
 * @param {string} gender — 'drenge' | 'piger'
 */
export function getClubsByGender(gender) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t => t.gender === gender))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}

/**
 * Get all clubs that have teams matching both age group and gender.
 */
export function findClubs({ ageGroup, gender } = {}) {
  return Object.entries(teams)
    .filter(([, v]) => v.teams.some(t =>
      (!ageGroup || t.ageGroup === ageGroup) &&
      (!gender   || t.gender   === gender)
    ))
    .map(([dbuId, v]) => ({ dbuId: Number(dbuId), name: v.name }));
}
`;

writeFileSync('teams.js', output, 'utf8');
console.log(`✓ teams.js written (${Object.keys(raw).length} clubs)`);
