/**
 * Generates figma-plugin/code.js from clubs.json.
 * Run with: node scripts/buildFigmaPlugin.js
 *
 * Then in Figma desktop:
 *   Main menu → Plugins → Development → Import plugin from manifest
 *   → select figma-plugin/manifest.json
 *   → Main menu → Plugins → Development → Club Badge Generator → Run
 */

import { readFileSync, writeFileSync } from 'fs';

const clubs = JSON.parse(readFileSync('clubs.json', 'utf8'))
  .map(({ name, dbuId }) => ({ name, dbuId }));

const FRAME_SIZE  = 500;
const FRAME_GAP   = 40;   // gap between frames in a row
const ROW_GAP     = 80;   // extra gap between letter groups
const LABEL_OFFSET = 90;  // how far left the letter label sits from x=0
const FONT_SIZE   = 28;
const TEXT_PAD    = 32;

const code = `
// Auto-generated by scripts/buildFigmaPlugin.js — do not edit by hand.

const clubs = ${JSON.stringify(clubs, null, 2)};

const FRAME_SIZE   = ${FRAME_SIZE};
const FRAME_GAP    = ${FRAME_GAP};
const ROW_GAP      = ${ROW_GAP};
const LABEL_OFFSET = ${LABEL_OFFSET};

async function main() {
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });

  // Build a set of dbuIds that already have a frame on this page
  const existingIds = new Set(
    figma.currentPage.children
      .filter(n => n.type === 'FRAME')
      .map(n => n.name)
  );

  const newClubs = clubs.filter(c => !existingIds.has(String(c.dbuId)));

  if (newClubs.length === 0) {
    figma.closePlugin('Nothing to add — all clubs already have frames.');
    return;
  }

  const nodes = [];

  // Map existing letter labels (single uppercase letter text nodes) to their Y position
  const letterRows = {};
  for (const node of figma.currentPage.children) {
    if (node.type === 'TEXT' && /^[A-ZÆØÅ]$/.test(node.characters)) {
      letterRows[node.characters] = node.y + node.height / 2 - FRAME_SIZE / 2; // row Y
    }
  }

  // Find the bottom of the canvas so new letter rows can be appended below
  const allFrames = figma.currentPage.children.filter(n => n.type === 'FRAME');
  let bottomY = allFrames.length > 0
    ? Math.max(...allFrames.map(f => f.y + f.height)) + ROW_GAP
    : 0;

  // Group NEW clubs by first letter
  const groups = [];
  for (const club of newClubs) {
    const letter = club.name[0].toUpperCase();
    if (!groups.length || groups[groups.length - 1].letter !== letter) {
      groups.push({ letter, clubs: [] });
    }
    groups[groups.length - 1].clubs.push(club);
  }

  for (const { letter, clubs: letterClubs } of groups) {
    let rowY;
    let startX;

    if (letterRows[letter] !== undefined) {
      // Letter row already exists — find the rightmost frame in that row and append after it
      rowY = letterRows[letter];
      const rowFrames = allFrames.filter(f => Math.abs(f.y - rowY) < FRAME_SIZE / 2);
      startX = rowFrames.length > 0
        ? Math.max(...rowFrames.map(f => f.x + f.width)) + FRAME_GAP
        : 0;
    } else {
      // New letter — create a label and start a new row at the bottom
      rowY = bottomY;
      startX = 0;
      letterRows[letter] = rowY;
      bottomY += FRAME_SIZE + ROW_GAP;

      const label = figma.createText();
      figma.currentPage.appendChild(label);
      label.characters = letter;
      label.fontSize   = 48;
      label.fontName   = { family: 'Inter', style: 'Bold' };
      label.fills      = [{ type: 'SOLID', color: { r: 0.7, g: 0.7, b: 0.7 } }];
      label.x          = -LABEL_OFFSET;
      label.y          = rowY + (FRAME_SIZE - label.height) / 2;
      nodes.push(label);
    }

    for (let i = 0; i < letterClubs.length; i++) {
      const { name, dbuId } = letterClubs[i];

      const frame = figma.createFrame();
      frame.name   = String(dbuId);
      frame.resize(FRAME_SIZE, FRAME_SIZE);
      frame.x      = startX + i * (FRAME_SIZE + FRAME_GAP);
      frame.y      = rowY;
      frame.fills  = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
      frame.clipsContent = false;
      // No export settings — add manually in Figma when a badge is finished

      const text = figma.createText();
      frame.appendChild(text);
      text.characters          = name;
      text.fontSize            = ${FONT_SIZE};
      text.fontName            = { family: 'Inter', style: 'Regular' };
      text.textAlignHorizontal = 'CENTER';
      text.fills               = [{ type: 'SOLID', color: { r: 0.15, g: 0.15, b: 0.15 } }];
      text.resize(FRAME_SIZE - ${TEXT_PAD * 2}, text.height);
      text.x = ${TEXT_PAD};
      text.y = (FRAME_SIZE - text.height) / 2;

      nodes.push(frame);
    }
  }

  figma.currentPage.selection = nodes;
  figma.viewport.scrollAndZoomIntoView(nodes);
  figma.closePlugin('Added ' + newClubs.length + ' new frames (' + (clubs.length - newClubs.length) + ' already existed).');
}

main();
`.trimStart();

writeFileSync('figma-plugin/code.js', code, 'utf8');
console.log(`✓ figma-plugin/code.js written (${clubs.length} clubs)`);
