/**
 * Reads clubs.json (after enrichMunicipalities.js has run) and writes
 * municipalities.js — a map of municipality name → [dbuId, …].
 *
 * Also writes municipalities.json for use by other scripts.
 *
 * Usage:
 *   node scripts/buildMunicipalities.js
 */

import { readFileSync, writeFileSync } from 'fs';

const BLOCKLIST = [
  /professional/i,
  /efterskole/i,
  /international school/i,
  /firmaidræt/i,
  /^10\./i,
  /10\. klasse/i,
  /10ende/i,
];

function isBlocked(name) {
  return BLOCKLIST.some(re => re.test(name));
}

const clubs = JSON.parse(readFileSync('clubs.json', 'utf8'));

// Build municipality → [dbuId] map, excluding blocked clubs
const map = {};
let blocked = 0;

for (const club of clubs) {
  if (!club.municipality || !club.dbuId) continue;
  if (isBlocked(club.name)) { blocked++; continue; }
  if (!map[club.municipality]) map[club.municipality] = [];
  map[club.municipality].push(club.dbuId);
}

const municipalityNames = Object.keys(map).sort((a, b) => a.localeCompare(b, 'da'));

writeFileSync('municipalities.json', JSON.stringify({ municipalities: map }, null, 2));

const output = `// Generated by scripts/buildMunicipalities.js — do not edit by hand.
// Municipality → dbuId groupings derived from clubs.json + DAWA postal lookup.

export const municipalities = ${JSON.stringify(map, null, 2)};

/**
 * Get the municipality name for a given dbuId.
 * Returns null if not found.
 */
export function getMunicipality(dbuId) {
  for (const [name, ids] of Object.entries(municipalities)) {
    if (ids.includes(dbuId)) return name;
  }
  return null;
}

/**
 * Get all dbuIds in a given municipality.
 */
export function getClubsByMunicipality(name) {
  return municipalities[name] ?? [];
}

/**
 * List all municipality names, sorted alphabetically.
 */
export function listMunicipalities() {
  return ${JSON.stringify(municipalityNames)};
}
`;

writeFileSync('municipalities.js', output, 'utf8');
console.log(`✓ municipalities.js written`);
console.log(`  ${municipalityNames.length} municipalities`);
console.log(`  ${Object.values(map).flat().length} clubs included`);
console.log(`  ${blocked} clubs blocked by name pattern`);
