// Auto-generated by scripts/buildFigmaPlugin.js — do not edit by hand.

const clubs = [
  {
    "name": "AB",
    "dbuId": 3711
  },
  {
    "name": "AB Tårnby",
    "dbuId": 1537
  },
  {
    "name": "Abild IF",
    "dbuId": 1728
  },
  {
    "name": "AC Horsens",
    "dbuId": 3715
  },
  {
    "name": "AC Iben",
    "dbuId": 3128
  },
  {
    "name": "Adventure Efterskole",
    "dbuId": 2739
  },
  {
    "name": "Agedrup-Bullerup Boldklub",
    "dbuId": 2101
  },
  {
    "name": "AGF",
    "dbuId": 3699
  },
  {
    "name": "Ahi International School",
    "dbuId": 3449
  },
  {
    "name": "AIK 65 Strøby Fodbold",
    "dbuId": 1251
  },
  {
    "name": "Allested U & IF",
    "dbuId": 1356
  },
  {
    "name": "Allesø GF",
    "dbuId": 1357
  },
  {
    "name": "Allinge-Sandvig G.F.",
    "dbuId": 1671
  },
  {
    "name": "Amager Fodbold Forening",
    "dbuId": 1538
  },
  {
    "name": "Amager International School",
    "dbuId": 3772
  },
  {
    "name": "Ammitsbøl/Egtved",
    "dbuId": 3276
  },
  {
    "name": "Arctos",
    "dbuId": 3237
  },
  {
    "name": "Aros FC",
    "dbuId": 3389
  },
  {
    "name": "Arrild Idrætsforening",
    "dbuId": 3423
  },
  {
    "name": "Artium, Brande",
    "dbuId": 2868
  },
  {
    "name": "Assens FC",
    "dbuId": 1358
  },
  {
    "name": "Aunslev IF",
    "dbuId": 1359
  },
  {
    "name": "Avarta",
    "dbuId": 3720
  },
  {
    "name": "B 1908",
    "dbuId": 3721
  },
  {
    "name": "B 1909",
    "dbuId": 1364
  },
  {
    "name": "B 1938",
    "dbuId": 1637
  },
  {
    "name": "B 1990",
    "dbuId": 1649
  },
  {
    "name": "B 65 OB",
    "dbuId": 3394
  },
  {
    "name": "B 67",
    "dbuId": 1366
  },
  {
    "name": "B 93",
    "dbuId": 3722
  },
  {
    "name": "B Chang",
    "dbuId": 1367
  },
  {
    "name": "B. 73, Slagelse",
    "dbuId": 1227
  },
  {
    "name": "B. 77, Rødovre",
    "dbuId": 1202
  },
  {
    "name": "B. 82, Virum",
    "dbuId": 1312
  },
  {
    "name": "B. Frem",
    "dbuId": 1654
  },
  {
    "name": "B1913",
    "dbuId": 1365
  },
  {
    "name": "Balle Musik- og Idrætsefterskole",
    "dbuId": 1923
  },
  {
    "name": "Ballerup Boldklub",
    "dbuId": 3921
  },
  {
    "name": "Ballerup-Skovlunde Fodbold",
    "dbuId": 2131
  },
  {
    "name": "Beboerprojekt Bispebjerg",
    "dbuId": 3758
  },
  {
    "name": "BGI Akademiet",
    "dbuId": 1924
  },
  {
    "name": "Billum IF",
    "dbuId": 3688
  },
  {
    "name": "Birkende BK",
    "dbuId": 1361
  },
  {
    "name": "Birket Boldklub",
    "dbuId": 1624
  },
  {
    "name": "Bispebjerg Boldklub",
    "dbuId": 1542
  },
  {
    "name": "Bjergsnæs Efterskole",
    "dbuId": 3764
  },
  {
    "name": "Bjørns International School",
    "dbuId": 2215
  },
  {
    "name": "BK 10",
    "dbuId": 2149
  },
  {
    "name": "BK 96, Solrød",
    "dbuId": 1237
  },
  {
    "name": "BK Frem",
    "dbuId": 3742
  },
  {
    "name": "BK Posten",
    "dbuId": 1470
  },
  {
    "name": "BK Stjernen af 1968",
    "dbuId": 1493
  },
  {
    "name": "BK Vest, Rødovre",
    "dbuId": 1304
  },
  {
    "name": "BK Vestfyn",
    "dbuId": 1369
  },
  {
    "name": "BK-06 Esbjerg",
    "dbuId": 1866
  },
  {
    "name": "BK2020",
    "dbuId": 1486
  },
  {
    "name": "Blidstrup Efterskole",
    "dbuId": 3005
  },
  {
    "name": "Blåhøj IF",
    "dbuId": 1714
  },
  {
    "name": "Blåkilde Efterskole",
    "dbuId": 2167
  },
  {
    "name": "Bogense G & IF",
    "dbuId": 1362
  },
  {
    "name": "Bogø IF",
    "dbuId": 1625
  },
  {
    "name": "Bolbro GIF",
    "dbuId": 1363
  },
  {
    "name": "Boldklubben 1903",
    "dbuId": 1533
  },
  {
    "name": "Boldklubben 1908",
    "dbuId": 1534
  },
  {
    "name": "Boldklubben 1960",
    "dbuId": 1536
  },
  {
    "name": "Boldklubben af 1893",
    "dbuId": 1532
  },
  {
    "name": "Boldklubben Amalie",
    "dbuId": 1540
  },
  {
    "name": "Boldklubben Døvania",
    "dbuId": 1603
  },
  {
    "name": "Boldklubben Enghaven",
    "dbuId": 3161
  },
  {
    "name": "Boldklubben Fix",
    "dbuId": 1599
  },
  {
    "name": "Boldklubben Frem",
    "dbuId": 1552
  },
  {
    "name": "Boldklubben Fremad Amager",
    "dbuId": 1553
  },
  {
    "name": "Boldklubben Fremad Valby",
    "dbuId": 1554
  },
  {
    "name": "Boldklubben Heimdal",
    "dbuId": 1559
  },
  {
    "name": "Boldklubben Hekla",
    "dbuId": 1560
  },
  {
    "name": "Boldklubben Marienlyst",
    "dbuId": 1444
  },
  {
    "name": "Boldklubben Olympia 1921",
    "dbuId": 1572
  },
  {
    "name": "Boldklubben Pioneren",
    "dbuId": 1573
  },
  {
    "name": "Boldklubben Rødovre",
    "dbuId": 1578
  },
  {
    "name": "Boldklubben Skjold",
    "dbuId": 1581
  },
  {
    "name": "Boldklubben Stefan",
    "dbuId": 1582
  },
  {
    "name": "Boldklubben Sundby KFUM",
    "dbuId": 1584
  },
  {
    "name": "Boldklubben Union",
    "dbuId": 1586
  },
  {
    "name": "Boldklubben Vestia",
    "dbuId": 1590
  },
  {
    "name": "Boldklubben Viktoria",
    "dbuId": 1592
  },
  {
    "name": "Boldklubben VLI",
    "dbuId": 1593
  },
  {
    "name": "Boldklubben Volvox",
    "dbuId": 1594
  },
  {
    "name": "Boreas",
    "dbuId": 3131
  },
  {
    "name": "Bork Havn Efterskole",
    "dbuId": 3444
  },
  {
    "name": "Brabrand IF",
    "dbuId": 3744
  },
  {
    "name": "Bramming Firmaidræt",
    "dbuId": 3338
  },
  {
    "name": "Bramming Gymnastik- og Idrætsefterskole",
    "dbuId": 2063
  },
  {
    "name": "Branderslev IF",
    "dbuId": 1626
  },
  {
    "name": "Brejning Efterskole",
    "dbuId": 2813
  },
  {
    "name": "Brejninggaard Efterskole",
    "dbuId": 2068
  },
  {
    "name": "Brenderup IF",
    "dbuId": 1370
  },
  {
    "name": "Broby Sportsefterskole",
    "dbuId": 2652
  },
  {
    "name": "Brylle BK",
    "dbuId": 1372
  },
  {
    "name": "Brøderup Efterskole",
    "dbuId": 3468
  },
  {
    "name": "Brøndby",
    "dbuId": 3700
  },
  {
    "name": "Brønshøj",
    "dbuId": 3712
  },
  {
    "name": "Brønshøj Boldklub",
    "dbuId": 1543
  },
  {
    "name": "Brøruphus Efterskole",
    "dbuId": 1943
  },
  {
    "name": "Bråskovgård Efterskole",
    "dbuId": 3112
  },
  {
    "name": "BUF Horsens",
    "dbuId": 2154
  },
  {
    "name": "Børneuniversitetet",
    "dbuId": 2230
  },
  {
    "name": "Bøvling Idrætsefterskole",
    "dbuId": 1939
  },
  {
    "name": "Båring GF",
    "dbuId": 1376
  },
  {
    "name": "Campus Vejle",
    "dbuId": 3880
  },
  {
    "name": "CBS Sport",
    "dbuId": 1602
  },
  {
    "name": "Center for Høretab",
    "dbuId": 2827
  },
  {
    "name": "Charlotteager Fodbold Klub",
    "dbuId": 3694
  },
  {
    "name": "Christiania Sports Club",
    "dbuId": 1545
  },
  {
    "name": "Christianshavns Idræts Klub",
    "dbuId": 1544
  },
  {
    "name": "Copenhagen Celtic",
    "dbuId": 3125
  },
  {
    "name": "Copenhagen City School",
    "dbuId": 3876
  },
  {
    "name": "DAI - Fodbold",
    "dbuId": 2099
  },
  {
    "name": "Dalby IF",
    "dbuId": 1377
  },
  {
    "name": "Dalum IF",
    "dbuId": 1378
  },
  {
    "name": "Dana Cup Sports Center",
    "dbuId": 3837
  },
  {
    "name": "Dansk Træner Union",
    "dbuId": 3146
  },
  {
    "name": "Dejbjerglund Efterskole",
    "dbuId": 1940
  },
  {
    "name": "Den Danske Husflidsefterskole",
    "dbuId": 2114
  },
  {
    "name": "Den Danske Husflidsefterskole (Dhe)",
    "dbuId": 2885
  },
  {
    "name": "Deportivo Cobayas",
    "dbuId": 3362
  },
  {
    "name": "Design- & Idrætsefterskolen Skamling",
    "dbuId": 1949
  },
  {
    "name": "Det Kgl. Vajsenhus",
    "dbuId": 2206
  },
  {
    "name": "Deutsche Nachschule Tingleff",
    "dbuId": 2771
  },
  {
    "name": "DGF Flensborg",
    "dbuId": 1903
  },
  {
    "name": "DGI Midtjylland",
    "dbuId": 3336
  },
  {
    "name": "DGI Nordvest",
    "dbuId": 3355
  },
  {
    "name": "DGI Sydvest",
    "dbuId": 3341
  },
  {
    "name": "Djursland Fodbolddommerklub",
    "dbuId": 3288
  },
  {
    "name": "Djurslands Efterskole",
    "dbuId": 1999
  },
  {
    "name": "Dover GF",
    "dbuId": 1888
  },
  {
    "name": "Dragør Boldklub",
    "dbuId": 1548
  },
  {
    "name": "Drigstrup BK",
    "dbuId": 1381
  },
  {
    "name": "Dronningborg Oldboys",
    "dbuId": 3238
  },
  {
    "name": "Døllefjelde Musse IF",
    "dbuId": 1627
  },
  {
    "name": "Ebberup IF",
    "dbuId": 1383
  },
  {
    "name": "Efterskolen Solgården",
    "dbuId": 2869
  },
  {
    "name": "Efterskolen Ådalen",
    "dbuId": 3759
  },
  {
    "name": "Egebjerg Fodbold",
    "dbuId": 1384
  },
  {
    "name": "Egmont Rollators FC",
    "dbuId": 1747
  },
  {
    "name": "Ejby IK",
    "dbuId": 1386
  },
  {
    "name": "Elbæk Efterskole",
    "dbuId": 1947
  },
  {
    "name": "Elite Bornholm",
    "dbuId": 2126
  },
  {
    "name": "Errindlev G & I",
    "dbuId": 1628
  },
  {
    "name": "Esbjerg",
    "dbuId": 3701
  },
  {
    "name": "Esbjerg Firmaidræt",
    "dbuId": 3337
  },
  {
    "name": "Eskilstrup BK",
    "dbuId": 1629
  },
  {
    "name": "EUC Nordvest",
    "dbuId": 3340
  },
  {
    "name": "F.C. Gladsaxe",
    "dbuId": 1316
  },
  {
    "name": "F.C. Lange Bolde",
    "dbuId": 3367
  },
  {
    "name": "F.C. Vesterbro",
    "dbuId": 3937
  },
  {
    "name": "FA 2000",
    "dbuId": 1546
  },
  {
    "name": "Faldsled/Svanninge SG & IF",
    "dbuId": 1392
  },
  {
    "name": "Farsø Efterskole",
    "dbuId": 3443
  },
  {
    "name": "FC Avrasya",
    "dbuId": 1511
  },
  {
    "name": "FC Bedem",
    "dbuId": 1854
  },
  {
    "name": "FC BiH Odense",
    "dbuId": 1893
  },
  {
    "name": "FC Broby",
    "dbuId": 1451
  },
  {
    "name": "FC Bøgeskov",
    "dbuId": 3951
  },
  {
    "name": "FC Campus",
    "dbuId": 1388
  },
  {
    "name": "FC Culpa",
    "dbuId": 1607
  },
  {
    "name": "FC Damsø",
    "dbuId": 1547
  },
  {
    "name": "FC Fredericia",
    "dbuId": 3713
  },
  {
    "name": "FC Faaborg",
    "dbuId": 1399
  },
  {
    "name": "FC Galaksi",
    "dbuId": 3826
  },
  {
    "name": "FC Glesborg",
    "dbuId": 3868
  },
  {
    "name": "FC Helsingør",
    "dbuId": 1781
  },
  {
    "name": "FC Helsingør",
    "dbuId": 3745
  },
  {
    "name": "FC Hjallese",
    "dbuId": 1389
  },
  {
    "name": "FC Holte",
    "dbuId": 1764
  },
  {
    "name": "FC Hornstrup",
    "dbuId": 3861
  },
  {
    "name": "FC Ishøj",
    "dbuId": 1878
  },
  {
    "name": "FC Knöedel",
    "dbuId": 3173
  },
  {
    "name": "FC Kurant",
    "dbuId": 1436
  },
  {
    "name": "FC København",
    "dbuId": 3710
  },
  {
    "name": "FC Lejre",
    "dbuId": 3422
  },
  {
    "name": "FC Midtjylland",
    "dbuId": 3705
  },
  {
    "name": "FC Nakskov",
    "dbuId": 3851
  },
  {
    "name": "FC Nanoq",
    "dbuId": 1759
  },
  {
    "name": "FC Nordsjælland",
    "dbuId": 3702
  },
  {
    "name": "FC Nyhavn",
    "dbuId": 1611
  },
  {
    "name": "FC Odense",
    "dbuId": 1390
  },
  {
    "name": "FC Olympiakos København",
    "dbuId": 3169
  },
  {
    "name": "FC Roskilde",
    "dbuId": 3731
  },
  {
    "name": "FC Ryparken",
    "dbuId": 1535
  },
  {
    "name": "FC SevenOaks",
    "dbuId": 2143
  },
  {
    "name": "FC Soccersisters",
    "dbuId": 3928
  },
  {
    "name": "FC Stalden",
    "dbuId": 1713
  },
  {
    "name": "FC Storebælt",
    "dbuId": 2031
  },
  {
    "name": "FC Sydfyn",
    "dbuId": 1393
  },
  {
    "name": "FC Sydvest 05 Tønder",
    "dbuId": 3750
  },
  {
    "name": "FC Udfordringen",
    "dbuId": 1755
  },
  {
    "name": "FC Udvikling",
    "dbuId": 3364
  },
  {
    "name": "FC Ypsilon",
    "dbuId": 1318
  },
  {
    "name": "FC Åben Modus",
    "dbuId": 2043
  },
  {
    "name": "FF Klettar",
    "dbuId": 3381
  },
  {
    "name": "Fiktiv",
    "dbuId": 1779
  },
  {
    "name": "FIUK, Odense",
    "dbuId": 3155
  },
  {
    "name": "Fjelsted/Harndrup IF",
    "dbuId": 1394
  },
  {
    "name": "Fjordager IF",
    "dbuId": 1395
  },
  {
    "name": "FK Odsherred",
    "dbuId": 2082
  },
  {
    "name": "FK Sydsjælland 05",
    "dbuId": 1750
  },
  {
    "name": "FK Utopia",
    "dbuId": 1516
  },
  {
    "name": "Flamengo Garrinchas",
    "dbuId": 3325
  },
  {
    "name": "Flemløse BK",
    "dbuId": 1396
  },
  {
    "name": "Flemming Efterskole",
    "dbuId": 1699
  },
  {
    "name": "FodboldHoldet Herning",
    "dbuId": 3839
  },
  {
    "name": "Fodboldklubben Prespa",
    "dbuId": 1576
  },
  {
    "name": "Fodboldklubben Sorø Freja",
    "dbuId": 1240
  },
  {
    "name": "Football Festival Denmark",
    "dbuId": 2168
  },
  {
    "name": "Fortuna 74",
    "dbuId": 3132
  },
  {
    "name": "Fortuna Hjørring",
    "dbuId": 3738
  },
  {
    "name": "Fortuna Svendborg",
    "dbuId": 3162
  },
  {
    "name": "Fr.holm Sydhavnen",
    "dbuId": 1609
  },
  {
    "name": "Fraugde G & IF",
    "dbuId": 1397
  },
  {
    "name": "Frederiksberg Boldklub",
    "dbuId": 1549
  },
  {
    "name": "Frederiksborg Amts",
    "dbuId": 2078
  },
  {
    "name": "Frederiksværk Fodbold Klub",
    "dbuId": 1749
  },
  {
    "name": "Freja’s Old Boys",
    "dbuId": 3252
  },
  {
    "name": "Fremad Amager Elite",
    "dbuId": 3743
  },
  {
    "name": "Fremad Forsing",
    "dbuId": 3831
  },
  {
    "name": "Frydensberg Efterskole",
    "dbuId": 2916
  },
  {
    "name": "Frøstruphave Efterskole",
    "dbuId": 3445
  },
  {
    "name": "Fuglsang IF",
    "dbuId": 3684
  },
  {
    "name": "Futsal Club Fjordbold",
    "dbuId": 3419
  },
  {
    "name": "Galtrup Efterskole",
    "dbuId": 2083
  },
  {
    "name": "Gelsted G & IF",
    "dbuId": 1400
  },
  {
    "name": "Gentofte Fodboldklub",
    "dbuId": 1555
  },
  {
    "name": "Gentofte-Vangede Idrætsforening",
    "dbuId": 1556
  },
  {
    "name": "Giovani Hajduk",
    "dbuId": 2035
  },
  {
    "name": "Gislev IF",
    "dbuId": 1401
  },
  {
    "name": "Glamsbjerg IF",
    "dbuId": 1402
  },
  {
    "name": "Glejbjerg Firmaidræt",
    "dbuId": 3352
  },
  {
    "name": "Glostrup FK - IF 32",
    "dbuId": 1712
  },
  {
    "name": "Glumsø",
    "dbuId": 2119
  },
  {
    "name": "Gram Efterskole",
    "dbuId": 2086
  },
  {
    "name": "Grasshopperne",
    "dbuId": 3245
  },
  {
    "name": "Grejsdalens Efterskole",
    "dbuId": 2866
  },
  {
    "name": "Gudenaadalens Efterskole",
    "dbuId": 2017
  },
  {
    "name": "Guldborg IF",
    "dbuId": 1631
  },
  {
    "name": "Gylling Efterskole",
    "dbuId": 2065
  },
  {
    "name": "Gødvad Efterskole",
    "dbuId": 3768
  },
  {
    "name": "Gørlev Idrætsefterskole",
    "dbuId": 1351
  },
  {
    "name": "Hald Ege Efterskole",
    "dbuId": 1934
  },
  {
    "name": "Halstedhus Efterskole",
    "dbuId": 2600
  },
  {
    "name": "Halstedhus IF",
    "dbuId": 3953
  },
  {
    "name": "Hammerum Fri- og Efterskole",
    "dbuId": 1930
  },
  {
    "name": "Han Herred Efterskoles Fodboldforening",
    "dbuId": 3272
  },
  {
    "name": "Handelsstandens Boldklub",
    "dbuId": 1558
  },
  {
    "name": "Hardsyssel Efterskole",
    "dbuId": 2115
  },
  {
    "name": "Hasle IF",
    "dbuId": 1673
  },
  {
    "name": "Haslev Idrætsefterskole",
    "dbuId": 3946
  },
  {
    "name": "HB Køge",
    "dbuId": 3714
  },
  {
    "name": "Hedemølle Efterskole",
    "dbuId": 3942
  },
  {
    "name": "Hellas",
    "dbuId": 1561
  },
  {
    "name": "Hellebjerg Idrætsefterskole",
    "dbuId": 1935
  },
  {
    "name": "Hellerup Idræts Klub",
    "dbuId": 1562
  },
  {
    "name": "Herborg Ungdomsforening",
    "dbuId": 2004
  },
  {
    "name": "Herlufmagle",
    "dbuId": 2121
  },
  {
    "name": "Herning Fodbolddommerklub",
    "dbuId": 3345
  },
  {
    "name": "Herrested-Ørbæk Boldklub",
    "dbuId": 1407
  },
  {
    "name": "Hesselager Fodbold",
    "dbuId": 1410
  },
  {
    "name": "Hestlund Efterskole",
    "dbuId": 2882
  },
  {
    "name": "HIK",
    "dbuId": 3723
  },
  {
    "name": "Himmerlandscentrets Idrætsefterskole (Haverslev)",
    "dbuId": 1937
  },
  {
    "name": "Historie Fremad",
    "dbuId": 3124
  },
  {
    "name": "Hjembæk Efterskole",
    "dbuId": 3881
  },
  {
    "name": "Hjemly Idrætsefterskole",
    "dbuId": 3944
  },
  {
    "name": "Hjørring Ny 10. klasse",
    "dbuId": 3051
  },
  {
    "name": "Hobro IK",
    "dbuId": 3704
  },
  {
    "name": "Holbæk",
    "dbuId": 3724
  },
  {
    "name": "Holbæk 10. klassecenter",
    "dbuId": 2540
  },
  {
    "name": "Holeby IF",
    "dbuId": 1633
  },
  {
    "name": "Holluf Pile-Tornbjerg IF",
    "dbuId": 1411
  },
  {
    "name": "Holm FK",
    "dbuId": 1743
  },
  {
    "name": "Holme-Olstrup Fodbold",
    "dbuId": 1870
  },
  {
    "name": "Holstebro/Vestjysk Fodbolddommerklub",
    "dbuId": 3344
  },
  {
    "name": "Holte-Hus Efterskole",
    "dbuId": 2360
  },
  {
    "name": "Horbelev IF",
    "dbuId": 1634
  },
  {
    "name": "Horne f. Sp.",
    "dbuId": 1412
  },
  {
    "name": "Horsens Fodbolddommerklub",
    "dbuId": 3346
  },
  {
    "name": "Horsens Motionsklub",
    "dbuId": 3675
  },
  {
    "name": "Horslunde BK",
    "dbuId": 1635
  },
  {
    "name": "Hospitalets FK",
    "dbuId": 1413
  },
  {
    "name": "Hou Maritime Idrætsefterskole",
    "dbuId": 1928
  },
  {
    "name": "Humble BK",
    "dbuId": 1414
  },
  {
    "name": "Husum Boldklub",
    "dbuId": 1563
  },
  {
    "name": "Hvidovre Idrætsforening",
    "dbuId": 1564
  },
  {
    "name": "Hvidovre IF",
    "dbuId": 3716
  },
  {
    "name": "Højby S & G",
    "dbuId": 1416
  },
  {
    "name": "Høje-Taastrup Linie 10",
    "dbuId": 2334
  },
  {
    "name": "Højer Efterskole",
    "dbuId": 1936
  },
  {
    "name": "Høng  Efterskole",
    "dbuId": 2544
  },
  {
    "name": "Hørby Efterskoles IF",
    "dbuId": 2014
  },
  {
    "name": "Høsterkøb Fodboldklub 2000",
    "dbuId": 2062
  },
  {
    "name": "Haarby Efterskole",
    "dbuId": 3933
  },
  {
    "name": "Haarby IF",
    "dbuId": 1418
  },
  {
    "name": "Hårslev BK",
    "dbuId": 1419
  },
  {
    "name": "Hårslev Efterskole",
    "dbuId": 3798
  },
  {
    "name": "Idræt og Venskab Foreningen, Århus",
    "dbuId": 1782
  },
  {
    "name": "Idrætsefterskolen Klintsøgaard",
    "dbuId": 3948
  },
  {
    "name": "Idrætsefterskolen Lægården",
    "dbuId": 1932
  },
  {
    "name": "IF Føroyar",
    "dbuId": 1606
  },
  {
    "name": "IF Svend Gønge",
    "dbuId": 1256
  },
  {
    "name": "Ingstrup Efterskoles IF",
    "dbuId": 3242
  },
  {
    "name": "Institut Sankt Joseph",
    "dbuId": 2207
  },
  {
    "name": "Iqbal International School",
    "dbuId": 2222
  },
  {
    "name": "IS Skævinge",
    "dbuId": 1226
  },
  {
    "name": "Isbryderen",
    "dbuId": 2234
  },
  {
    "name": "ISI Idrætsefterskole",
    "dbuId": 3649
  },
  {
    "name": "Isterød Efterskole",
    "dbuId": 2451
  },
  {
    "name": "Janderup IF",
    "dbuId": 3687
  },
  {
    "name": "Jetsmark Idrætscenter",
    "dbuId": 3657
  },
  {
    "name": "JIK-Esbjerg",
    "dbuId": 3685
  },
  {
    "name": "Jinnah International School",
    "dbuId": 3799
  },
  {
    "name": "Jægersborg Boldklub",
    "dbuId": 1565
  },
  {
    "name": "Jødisk Idrætsforening Hakoah",
    "dbuId": 1557
  },
  {
    "name": "Karup/Kølvrå 07",
    "dbuId": 1955
  },
  {
    "name": "Kastrup Boldklub",
    "dbuId": 1566
  },
  {
    "name": "Katrinebjergs Atletikforening",
    "dbuId": 3843
  },
  {
    "name": "Kauslunde IF",
    "dbuId": 1422
  },
  {
    "name": "Kerte GF",
    "dbuId": 1423
  },
  {
    "name": "Kerteminde BK",
    "dbuId": 1424
  },
  {
    "name": "Kerteminde Efterskole",
    "dbuId": 2663
  },
  {
    "name": "KFUM.s BK Odense",
    "dbuId": 1425
  },
  {
    "name": "KFUMs Boldklub",
    "dbuId": 1569
  },
  {
    "name": "Kildemosens BK",
    "dbuId": 1426
  },
  {
    "name": "Kildevæld Efterskole",
    "dbuId": 3870
  },
  {
    "name": "Kirkeby IF",
    "dbuId": 1427
  },
  {
    "name": "Kirkeholdet Vrå",
    "dbuId": 3663
  },
  {
    "name": "Kjøbenhavns Boldklub",
    "dbuId": 1567
  },
  {
    "name": "Klank Efterskole (fodbold)",
    "dbuId": 2087
  },
  {
    "name": "Klemensker IF",
    "dbuId": 1674
  },
  {
    "name": "Klinte Grindløse IF",
    "dbuId": 1428
  },
  {
    "name": "Klosterhallen",
    "dbuId": 3371
  },
  {
    "name": "Klub 14",
    "dbuId": 3833
  },
  {
    "name": "Klubrådgiverklubben",
    "dbuId": 1851
  },
  {
    "name": "Kløvermarkens Forenede Boldklubber",
    "dbuId": 1568
  },
  {
    "name": "Knudsker IF",
    "dbuId": 1675
  },
  {
    "name": "Kokkedal BK",
    "dbuId": 1837
  },
  {
    "name": "Koldingegnens Idrætsefterskole",
    "dbuId": 1938
  },
  {
    "name": "Kongenshus Efterskole",
    "dbuId": 2084
  },
  {
    "name": "Korinth IF",
    "dbuId": 1429
  },
  {
    "name": "KP Zebras",
    "dbuId": 3667
  },
  {
    "name": "KR 70",
    "dbuId": 1431
  },
  {
    "name": "Kragelund Efterskole",
    "dbuId": 1989
  },
  {
    "name": "Krarup Espe Fodbold",
    "dbuId": 1432
  },
  {
    "name": "Krusbjerg IF",
    "dbuId": 3686
  },
  {
    "name": "KSI - KU Studenteridræt",
    "dbuId": 3650
  },
  {
    "name": "KU BK",
    "dbuId": 1430
  },
  {
    "name": "Kvindedivisionsforeningen",
    "dbuId": 2124
  },
  {
    "name": "Kværndrup BK",
    "dbuId": 1437
  },
  {
    "name": "Kærby IF",
    "dbuId": 3376
  },
  {
    "name": "Kærbysport",
    "dbuId": 3117
  },
  {
    "name": "København Futsal",
    "dbuId": 2088
  },
  {
    "name": "Københavns Amts",
    "dbuId": 2079
  },
  {
    "name": "Køge FC",
    "dbuId": 1961
  },
  {
    "name": "Langebæk Alliancen",
    "dbuId": 3230
  },
  {
    "name": "Langeskov IF",
    "dbuId": 1438
  },
  {
    "name": "Langtved SG  &  IF",
    "dbuId": 1439
  },
  {
    "name": "Levring Efterskole",
    "dbuId": 1948
  },
  {
    "name": "Listrup U&IF",
    "dbuId": 1640
  },
  {
    "name": "Lomborg Gymnastik- og Idrætsefterskole",
    "dbuId": 1933
  },
  {
    "name": "Longelse Sp.",
    "dbuId": 1441
  },
  {
    "name": "Los Amigos",
    "dbuId": 3261
  },
  {
    "name": "Lumby IF 88",
    "dbuId": 1442
  },
  {
    "name": "Lundby Efterskole",
    "dbuId": 2637
  },
  {
    "name": "Lunderskov Efterskole",
    "dbuId": 1993
  },
  {
    "name": "Lyngby",
    "dbuId": 3717
  },
  {
    "name": "Lyngs Idrætsefterskole",
    "dbuId": 1931
  },
  {
    "name": "Læringshuset",
    "dbuId": 2330
  },
  {
    "name": "Løgumkloster Efterskole",
    "dbuId": 1990
  },
  {
    "name": "Mariager Efterskole",
    "dbuId": 2915
  },
  {
    "name": "Maribo BK",
    "dbuId": 1641
  },
  {
    "name": "Marslev G & IF",
    "dbuId": 1445
  },
  {
    "name": "Marstal IF",
    "dbuId": 1446
  },
  {
    "name": "Mejlby Efterskole",
    "dbuId": 3655
  },
  {
    "name": "Mellerup Efterskole",
    "dbuId": 2164
  },
  {
    "name": "MG & BK",
    "dbuId": 1447
  },
  {
    "name": "Midtjysk Efterskole",
    "dbuId": 3110
  },
  {
    "name": "Midtjysk Fodbolddommerklub",
    "dbuId": 3343
  },
  {
    "name": "Mina Hindholm Efterskole",
    "dbuId": 2545
  },
  {
    "name": "Moltrup IF",
    "dbuId": 1895
  },
  {
    "name": "Morud IF",
    "dbuId": 1448
  },
  {
    "name": "Munkebo BK",
    "dbuId": 1449
  },
  {
    "name": "Munkevængets Fritids- og IF",
    "dbuId": 1852
  },
  {
    "name": "Mørkhøj Sportsklub",
    "dbuId": 1276
  },
  {
    "name": "New City",
    "dbuId": 3819
  },
  {
    "name": "Nexø B.",
    "dbuId": 1676
  },
  {
    "name": "NFS - Nørremarkens forenede Sportsklubber",
    "dbuId": 3416
  },
  {
    "name": "Nislevgård Efterskole",
    "dbuId": 2713
  },
  {
    "name": "Nordborg Slots Efterskole",
    "dbuId": 2752
  },
  {
    "name": "Nordbyens Boldklub",
    "dbuId": 3385
  },
  {
    "name": "Nordfalster FB",
    "dbuId": 1644
  },
  {
    "name": "Nordsjællands Efterskole",
    "dbuId": 2422
  },
  {
    "name": "Nordvestjysk Fodbolddommerklub",
    "dbuId": 3342
  },
  {
    "name": "Nr. Lyndelse / Søby F.C.",
    "dbuId": 1452
  },
  {
    "name": "Nr. Nissum Efterskole",
    "dbuId": 2066
  },
  {
    "name": "Nr. Søby BK",
    "dbuId": 1453
  },
  {
    "name": "Nr. Aaby IK",
    "dbuId": 1454
  },
  {
    "name": "Ny Kappel Boldklub 07",
    "dbuId": 1951
  },
  {
    "name": "Nyborg G & IF",
    "dbuId": 1456
  },
  {
    "name": "Nyker IF",
    "dbuId": 1677
  },
  {
    "name": "Nykøbing FC",
    "dbuId": 3404
  },
  {
    "name": "Nykøbing FC",
    "dbuId": 3746
  },
  {
    "name": "Nysted Efterskole",
    "dbuId": 2614
  },
  {
    "name": "Næsby",
    "dbuId": 3726
  },
  {
    "name": "Næsby BK",
    "dbuId": 1457
  },
  {
    "name": "Næstved BK",
    "dbuId": 3727
  },
  {
    "name": "Nøddealliancen",
    "dbuId": 3734
  },
  {
    "name": "Nørbæk Efterskole",
    "dbuId": 2930
  },
  {
    "name": "Nørre Alslev BK",
    "dbuId": 1650
  },
  {
    "name": "Nørre Åby Efterskole",
    "dbuId": 3887
  },
  {
    "name": "Nørrebro Boldklub",
    "dbuId": 2089
  },
  {
    "name": "Nørrebro United",
    "dbuId": 1987
  },
  {
    "name": "Nøvlingskov Efterskole",
    "dbuId": 2064
  },
  {
    "name": "OB",
    "dbuId": 3706
  },
  {
    "name": "OB Q",
    "dbuId": 3938
  },
  {
    "name": "OB Turnering Næstved",
    "dbuId": 2157
  },
  {
    "name": "Odense Boldklub",
    "dbuId": 1458
  },
  {
    "name": "Odsherreds Efterskole",
    "dbuId": 2523
  },
  {
    "name": "Old Boys 1945",
    "dbuId": 2106
  },
  {
    "name": "Old Boys Cup 77",
    "dbuId": 2158
  },
  {
    "name": "Olympic Amager KIF - Afventer",
    "dbuId": 3144
  },
  {
    "name": "Ommel BK",
    "dbuId": 1464
  },
  {
    "name": "Ordblindeinstituttet",
    "dbuId": 2295
  },
  {
    "name": "Ore Sogns GF",
    "dbuId": 1465
  },
  {
    "name": "Osted Fri- og Efterskole",
    "dbuId": 3223
  },
  {
    "name": "Otterup Bold- og Idrætsklub",
    "dbuId": 1467
  },
  {
    "name": "Oure Fodbold Akademi",
    "dbuId": 1468
  },
  {
    "name": "Ove Lyhne",
    "dbuId": 1848
  },
  {
    "name": "Overvindinge",
    "dbuId": 3690
  },
  {
    "name": "Pan Fodbold",
    "dbuId": 1760
  },
  {
    "name": "Pedersker IF",
    "dbuId": 1679
  },
  {
    "name": "Pederstrup Efterskole",
    "dbuId": 2599
  },
  {
    "name": "Phønix Efterskole",
    "dbuId": 3586
  },
  {
    "name": "Politiets Idrætsforening",
    "dbuId": 1574
  },
  {
    "name": "Poulsker IF",
    "dbuId": 1680
  },
  {
    "name": "Radsted IF",
    "dbuId": 1651
  },
  {
    "name": "Randers ElitesportsCollege",
    "dbuId": 3228
  },
  {
    "name": "Randers FC",
    "dbuId": 3707
  },
  {
    "name": "Randers Fodbolddommerklub",
    "dbuId": 3347
  },
  {
    "name": "Ranum Efterskole",
    "dbuId": 2059
  },
  {
    "name": "Rebild Efterskole",
    "dbuId": 1991
  },
  {
    "name": "Rejsby Europæiske Efterskole",
    "dbuId": 1776
  },
  {
    "name": "Rikken Fodbold Club",
    "dbuId": 1577
  },
  {
    "name": "Ringe BK",
    "dbuId": 1472
  },
  {
    "name": "Ringe Efterskole",
    "dbuId": 3943
  },
  {
    "name": "Rinkenæs Efterskole",
    "dbuId": 2003
  },
  {
    "name": "Rise S & IF",
    "dbuId": 1475
  },
  {
    "name": "Rolfsted IF",
    "dbuId": 1477
  },
  {
    "name": "Roskilde Pigefodbold",
    "dbuId": 3696
  },
  {
    "name": "Rudbjerg FB",
    "dbuId": 1652
  },
  {
    "name": "Rudkøbing BK",
    "dbuId": 1478
  },
  {
    "name": "Ruds Vedby IF",
    "dbuId": 1200
  },
  {
    "name": "Ryslinge BK",
    "dbuId": 1479
  },
  {
    "name": "Rødby BK",
    "dbuId": 1653
  },
  {
    "name": "Røde Fane IF",
    "dbuId": 3137
  },
  {
    "name": "Røde Stjerne",
    "dbuId": 1480
  },
  {
    "name": "Røde Stjerne BK",
    "dbuId": 1201
  },
  {
    "name": "Rødvig G&I",
    "dbuId": 1203
  },
  {
    "name": "Rønde Efterskole",
    "dbuId": 1944
  },
  {
    "name": "Rønne f.B.",
    "dbuId": 1956
  },
  {
    "name": "Rønne IK",
    "dbuId": 1682
  },
  {
    "name": "Rønnebæk IF",
    "dbuId": 1204
  },
  {
    "name": "Rønnede IF",
    "dbuId": 1205
  },
  {
    "name": "Rønneholtparkens BK",
    "dbuId": 1206
  },
  {
    "name": "Rørby-Værslev IF",
    "dbuId": 1207
  },
  {
    "name": "Rørvig IF",
    "dbuId": 1208
  },
  {
    "name": "Rågelund Efterskole",
    "dbuId": 2709
  },
  {
    "name": "S.K.F.I.F.",
    "dbuId": 1488
  },
  {
    "name": "Sall IF",
    "dbuId": 3141
  },
  {
    "name": "Salling Efterskole",
    "dbuId": 3654
  },
  {
    "name": "Samsø Efterskole",
    "dbuId": 2946
  },
  {
    "name": "Sandby  GF",
    "dbuId": 1655
  },
  {
    "name": "Sanderum BK",
    "dbuId": 1481
  },
  {
    "name": "Sandved-Tornemark IF",
    "dbuId": 1209
  },
  {
    "name": "SBV 09",
    "dbuId": 3844
  },
  {
    "name": "SC Amager",
    "dbuId": 1892
  },
  {
    "name": "Sct. Jørgens IF",
    "dbuId": 1211
  },
  {
    "name": "Sdr. Bork Efterskole",
    "dbuId": 2870
  },
  {
    "name": "Sdr. Felding Efterskole",
    "dbuId": 2067
  },
  {
    "name": "Sdr. Nærå Fri- og Efterskole",
    "dbuId": 2734
  },
  {
    "name": "Sejerø IF",
    "dbuId": 1212
  },
  {
    "name": "Sengeløse GI",
    "dbuId": 1213
  },
  {
    "name": "SfB",
    "dbuId": 1497
  },
  {
    "name": "Sierslev FC",
    "dbuId": 1215
  },
  {
    "name": "SIF Holbæk IF",
    "dbuId": 1216
  },
  {
    "name": "Sigerslevøster IF",
    "dbuId": 1217
  },
  {
    "name": "Silkeborg",
    "dbuId": 3708
  },
  {
    "name": "Silkeborg Efterskole",
    "dbuId": 3765
  },
  {
    "name": "Silkeborg Fodbolddommerklub",
    "dbuId": 3348
  },
  {
    "name": "Silkeborg IF Q",
    "dbuId": 3400
  },
  {
    "name": "SINE Sportsefterskole",
    "dbuId": 1992
  },
  {
    "name": "SISU MBK Fodbold",
    "dbuId": 3859
  },
  {
    "name": "Sjællands",
    "dbuId": 2077
  },
  {
    "name": "Skalbjerg BK",
    "dbuId": 1482
  },
  {
    "name": "Skallebølle Sportsklub",
    "dbuId": 1483
  },
  {
    "name": "Skals Efterskole",
    "dbuId": 3763
  },
  {
    "name": "Skamby BK",
    "dbuId": 1484
  },
  {
    "name": "Skanderup Efterskole",
    "dbuId": 2020
  },
  {
    "name": "Skeby GF",
    "dbuId": 1485
  },
  {
    "name": "Skensved IF",
    "dbuId": 1219
  },
  {
    "name": "Skibby IK",
    "dbuId": 1220
  },
  {
    "name": "Skibelund Gymnastik- og Idrætsefterskole",
    "dbuId": 3845
  },
  {
    "name": "Skive IK",
    "dbuId": 3732
  },
  {
    "name": "Skjern Kulturcenter",
    "dbuId": 3368
  },
  {
    "name": "Skjød IF",
    "dbuId": 3241
  },
  {
    "name": "Skovbakken IK OB",
    "dbuId": 3246
  },
  {
    "name": "Skovbo Efterskole",
    "dbuId": 3606
  },
  {
    "name": "Skovby GF",
    "dbuId": 1487
  },
  {
    "name": "Skovlund Efterskole",
    "dbuId": 2165
  },
  {
    "name": "Skovlunde IF Oldboys/Girls",
    "dbuId": 1868
  },
  {
    "name": "Skovshoved Idrætsforening",
    "dbuId": 1579
  },
  {
    "name": "Skyum Idrætsefterskole",
    "dbuId": 2085
  },
  {
    "name": "Skælskør Boldklub og Idrætsforening",
    "dbuId": 1225
  },
  {
    "name": "Skærbæk Fritidscenter",
    "dbuId": 3370
  },
  {
    "name": "Skårup IF",
    "dbuId": 1489
  },
  {
    "name": "Slagelse B&I",
    "dbuId": 1229
  },
  {
    "name": "Slaglille-Bjernede GI",
    "dbuId": 1232
  },
  {
    "name": "Slagslunde-Ganløse IF",
    "dbuId": 1233
  },
  {
    "name": "Slangerup & Omegn IF",
    "dbuId": 1234
  },
  {
    "name": "Snekkersten IF",
    "dbuId": 1235
  },
  {
    "name": "Solrød FC",
    "dbuId": 1238
  },
  {
    "name": "Sommersted Efterskole",
    "dbuId": 2021
  },
  {
    "name": "Sorø Gymnastikefterskole",
    "dbuId": 2579
  },
  {
    "name": "Spir Efterskole",
    "dbuId": 3884
  },
  {
    "name": "Spjald Fritidscenter",
    "dbuId": 1965
  },
  {
    "name": "Sportsefterskolen Sjælsølund",
    "dbuId": 3954
  },
  {
    "name": "Sportsefterskolen Aabybro",
    "dbuId": 1996
  },
  {
    "name": "ST Oldboys, Trige",
    "dbuId": 3156
  },
  {
    "name": "Stenlille IF",
    "dbuId": 1242
  },
  {
    "name": "Stenløse BK",
    "dbuId": 1243
  },
  {
    "name": "Stenstrup IF",
    "dbuId": 1491
  },
  {
    "name": "Stidsholt IF (Efterskole)",
    "dbuId": 1694
  },
  {
    "name": "Stillinge IF",
    "dbuId": 1246
  },
  {
    "name": "Stokkemarke",
    "dbuId": 1656
  },
  {
    "name": "Store Heddinge BK",
    "dbuId": 1247
  },
  {
    "name": "Store Lyngby IF",
    "dbuId": 1248
  },
  {
    "name": "Store Merløse IF",
    "dbuId": 1249
  },
  {
    "name": "Strib Idrætsefterskole",
    "dbuId": 3949
  },
  {
    "name": "Strib IF",
    "dbuId": 1494
  },
  {
    "name": "Stubbekøbing BK",
    "dbuId": 1658
  },
  {
    "name": "Studenter Settlementets Boldklub",
    "dbuId": 1598
  },
  {
    "name": "STUK Overbygning",
    "dbuId": 2756
  },
  {
    "name": "SUB Ullerslev",
    "dbuId": 1496
  },
  {
    "name": "Sundby Boldklub",
    "dbuId": 1583
  },
  {
    "name": "Sundeved Efterskoles IF",
    "dbuId": 1950
  },
  {
    "name": "Suså IF",
    "dbuId": 1252
  },
  {
    "name": "Svaneke Idræts Klub",
    "dbuId": 1683
  },
  {
    "name": "Svendborg Efterskole",
    "dbuId": 3589
  },
  {
    "name": "Svinninge IF",
    "dbuId": 1257
  },
  {
    "name": "Svogerslev BK",
    "dbuId": 1258
  },
  {
    "name": "Syd- & Østsjællands",
    "dbuId": 2080
  },
  {
    "name": "Sydvestjyllands Efterskole Fodbold",
    "dbuId": 3273
  },
  {
    "name": "Sydvestjysk Fodbolddommerklub",
    "dbuId": 3351
  },
  {
    "name": "Sydøstjysk Fodbolddommerklub",
    "dbuId": 3350
  },
  {
    "name": "Systofte BK",
    "dbuId": 1660
  },
  {
    "name": "Sædder IF",
    "dbuId": 1261
  },
  {
    "name": "Sædding Efterskole",
    "dbuId": 3514
  },
  {
    "name": "Særslev BK",
    "dbuId": 1498
  },
  {
    "name": "Søhus IF",
    "dbuId": 2070
  },
  {
    "name": "Søllested IF",
    "dbuId": 1662
  },
  {
    "name": "Søllinge Sport og Fritid",
    "dbuId": 1501
  },
  {
    "name": "Sønderbro Fight",
    "dbuId": 1580
  },
  {
    "name": "Sønderjydsk Fodbolddommerklub",
    "dbuId": 3356
  },
  {
    "name": "SønderjyskE",
    "dbuId": 3703
  },
  {
    "name": "Søndersø BK",
    "dbuId": 1502
  },
  {
    "name": "SØS - Sydøstsjællands Idrætsefterskole",
    "dbuId": 3941
  },
  {
    "name": "Såby Fodbold",
    "dbuId": 1266
  },
  {
    "name": "Tarup/Paarup IF",
    "dbuId": 1503
  },
  {
    "name": "Team 2. Sal",
    "dbuId": 3957
  },
  {
    "name": "Team InterRos",
    "dbuId": 3830
  },
  {
    "name": "Team Viborg",
    "dbuId": 3850
  },
  {
    "name": "Tejn IF",
    "dbuId": 1684
  },
  {
    "name": "Terslev G&IF",
    "dbuId": 1267
  },
  {
    "name": "Thisted FC",
    "dbuId": 3747
  },
  {
    "name": "Thorsø OB",
    "dbuId": 3136
  },
  {
    "name": "Thurø BK af 1920",
    "dbuId": 1505
  },
  {
    "name": "Thyland idrætsefterskole",
    "dbuId": 2019
  },
  {
    "name": "Tikøb IF",
    "dbuId": 1270
  },
  {
    "name": "Tingsted BK",
    "dbuId": 1663
  },
  {
    "name": "Tirstrup Idrætsefterskole",
    "dbuId": 1945
  },
  {
    "name": "Tisvildeleje GF",
    "dbuId": 1271
  },
  {
    "name": "Tjele Efterskole",
    "dbuId": 3013
  },
  {
    "name": "Toksværd Olstrup Fodbold",
    "dbuId": 1958
  },
  {
    "name": "Tommerup BK",
    "dbuId": 1507
  },
  {
    "name": "Torpedo AT",
    "dbuId": 1858
  },
  {
    "name": "Torslunde-Ishøj IF",
    "dbuId": 1274
  },
  {
    "name": "Tranekær/Tullebølle IF",
    "dbuId": 1508
  },
  {
    "name": "TST Kunstgræsanlæg",
    "dbuId": 3265
  },
  {
    "name": "Tune IF",
    "dbuId": 1280
  },
  {
    "name": "Tuse IF",
    "dbuId": 1282
  },
  {
    "name": "Tuse Næs BK",
    "dbuId": 1283
  },
  {
    "name": "Tved BK",
    "dbuId": 1510
  },
  {
    "name": "Tølløse BK",
    "dbuId": 1284
  },
  {
    "name": "Tølløse Privat- og Efterskole",
    "dbuId": 2590
  },
  {
    "name": "Tømmerup Fri- og Efterskole",
    "dbuId": 2549
  },
  {
    "name": "Tømmerup GU",
    "dbuId": 1285
  },
  {
    "name": "Taarbæk IF",
    "dbuId": 1286
  },
  {
    "name": "Tårnby FF",
    "dbuId": 1766
  },
  {
    "name": "Tårup IF",
    "dbuId": 1512
  },
  {
    "name": "Tåsinge f. B.",
    "dbuId": 1513
  },
  {
    "name": "Taastrup FC",
    "dbuId": 1783
  },
  {
    "name": "Ubberud IF",
    "dbuId": 1514
  },
  {
    "name": "Ubby Fri- og Efterskole",
    "dbuId": 3892
  },
  {
    "name": "Uganda Danish Cranes FC",
    "dbuId": 3751
  },
  {
    "name": "Ugelbølle IF",
    "dbuId": 3133
  },
  {
    "name": "Uggerby Idrætsforening",
    "dbuId": 3678
  },
  {
    "name": "Undløse BK",
    "dbuId": 1290
  },
  {
    "name": "Unge Hjems Efterskole",
    "dbuId": 3225
  },
  {
    "name": "Ungeuniverset-Vojens",
    "dbuId": 3307
  },
  {
    "name": "Unionshold",
    "dbuId": 1670
  },
  {
    "name": "University College Lillebælt Football Club",
    "dbuId": 3840
  },
  {
    "name": "US10 Tårnby",
    "dbuId": 2373
  },
  {
    "name": "Uvelse IF",
    "dbuId": 1291
  },
  {
    "name": "Valby Boldklub",
    "dbuId": 1587
  },
  {
    "name": "Vallensbæk IF",
    "dbuId": 1292
  },
  {
    "name": "Vallensved",
    "dbuId": 2120
  },
  {
    "name": "Vandel Efterskole",
    "dbuId": 1894
  },
  {
    "name": "Vanløse Idræts Forening",
    "dbuId": 1588
  },
  {
    "name": "Vapnagård FK 72",
    "dbuId": 1295
  },
  {
    "name": "Vedersø Efterskole",
    "dbuId": 3651
  },
  {
    "name": "Veflinge G &  IF",
    "dbuId": 1518
  },
  {
    "name": "Vejby IF",
    "dbuId": 1298
  },
  {
    "name": "Vejen 10.",
    "dbuId": 3781
  },
  {
    "name": "Vejle Boldklub",
    "dbuId": 3718
  },
  {
    "name": "Vejle Fodbolddommerklub",
    "dbuId": 2094
  },
  {
    "name": "Vejle Idrætsefterskole",
    "dbuId": 1941
  },
  {
    "name": "Veksø IF",
    "dbuId": 1301
  },
  {
    "name": "Vemmelev BK",
    "dbuId": 1303
  },
  {
    "name": "Vendsyssel FF",
    "dbuId": 3733
  },
  {
    "name": "Vendsyssel Fodbolddommerklub",
    "dbuId": 3349
  },
  {
    "name": "Verninge IF",
    "dbuId": 1519
  },
  {
    "name": "Vestbirk Musik- & Sportsefterskole",
    "dbuId": 1994
  },
  {
    "name": "Vesterborg Efterskole",
    "dbuId": 3811
  },
  {
    "name": "Vesterbro Alliancen",
    "dbuId": 1604
  },
  {
    "name": "Vesterlund Efterskole",
    "dbuId": 3107
  },
  {
    "name": "Vestsjællands Amts",
    "dbuId": 2081
  },
  {
    "name": "Vestsjællands idrætsefterskole",
    "dbuId": 3947
  },
  {
    "name": "Veteranturneringen Sydsjælland-Møn",
    "dbuId": 2159
  },
  {
    "name": "Vetterslev-Høm GF",
    "dbuId": 1306
  },
  {
    "name": "Viborg",
    "dbuId": 3719
  },
  {
    "name": "Viborg FF Oldboys 2003",
    "dbuId": 1702
  },
  {
    "name": "Vigerslev Boldklub",
    "dbuId": 1591
  },
  {
    "name": "Viking Fodbold",
    "dbuId": 1685
  },
  {
    "name": "Vildbjerg Sports- & Kulturcenter",
    "dbuId": 1976
  },
  {
    "name": "Vindinge BK",
    "dbuId": 1523
  },
  {
    "name": "Vindinge IF",
    "dbuId": 1310
  },
  {
    "name": "Vipperød BK",
    "dbuId": 1311
  },
  {
    "name": "Virum-Sorgenfri BK",
    "dbuId": 1313
  },
  {
    "name": "Vissenbjerg G & IF",
    "dbuId": 1524
  },
  {
    "name": "Vittrup Efterskole - Lukket ??",
    "dbuId": 2060
  },
  {
    "name": "Vivild Gymnastik- og Idrætsefterskole",
    "dbuId": 1946
  },
  {
    "name": "Vojens Gymnastik- & Idrætsefterskole",
    "dbuId": 2013
  },
  {
    "name": "Vor Frue IF",
    "dbuId": 1315
  },
  {
    "name": "Vordingborg IF",
    "dbuId": 1314
  },
  {
    "name": "Vrigsted Efterskole",
    "dbuId": 3108
  },
  {
    "name": "Vrå Undervisningscenter",
    "dbuId": 3057
  },
  {
    "name": "Væggerløse BK",
    "dbuId": 1667
  },
  {
    "name": "Værløse BK",
    "dbuId": 1317
  },
  {
    "name": "Walther F.C.",
    "dbuId": 3846
  },
  {
    "name": "ØKF",
    "dbuId": 1596
  },
  {
    "name": "Ølgod Efterskole",
    "dbuId": 2166
  },
  {
    "name": "Ølsted IF",
    "dbuId": 1321
  },
  {
    "name": "Ølstykke FC",
    "dbuId": 1322
  },
  {
    "name": "Ørestad IF",
    "dbuId": 3357
  },
  {
    "name": "Ørslev GIF (V)",
    "dbuId": 1324
  },
  {
    "name": "Ørslev-Bjerge IF",
    "dbuId": 1326
  },
  {
    "name": "Ørslev-Solbjerg IF",
    "dbuId": 1327
  },
  {
    "name": "Øster Ulslev BK",
    "dbuId": 1668
  },
  {
    "name": "Østerbro Idræts Forening",
    "dbuId": 1595
  },
  {
    "name": "Østerlars B.",
    "dbuId": 1686
  },
  {
    "name": "Østermarie IF",
    "dbuId": 1687
  },
  {
    "name": "Østmøn SGI",
    "dbuId": 1328
  },
  {
    "name": "Østofte GIF (PASSIV)",
    "dbuId": 1669
  },
  {
    "name": "AaB",
    "dbuId": 3698
  },
  {
    "name": "Ågård Efterskole",
    "dbuId": 2018
  },
  {
    "name": "Aakanden GF",
    "dbuId": 3358
  },
  {
    "name": "Åkirkeby IF",
    "dbuId": 1688
  },
  {
    "name": "Aalborg Firmaidræt",
    "dbuId": 3353
  },
  {
    "name": "Aalborg Fodbolddommerklub",
    "dbuId": 3139
  },
  {
    "name": "Aalborg Fremad",
    "dbuId": 3939
  },
  {
    "name": "Aalborg Futsal Klub",
    "dbuId": 3417
  },
  {
    "name": "Ålholm IF",
    "dbuId": 1329
  },
  {
    "name": "Ålum IF",
    "dbuId": 3134
  },
  {
    "name": "Årby GI",
    "dbuId": 1330
  },
  {
    "name": "Aarhus Black Vipers",
    "dbuId": 3818
  },
  {
    "name": "Aarhus Fodbolddommerklub",
    "dbuId": 2093
  },
  {
    "name": "Aarhus Fremad",
    "dbuId": 3729
  },
  {
    "name": "Aarsballe B.",
    "dbuId": 1689
  },
  {
    "name": "Aarslev BK",
    "dbuId": 1528
  },
  {
    "name": "Aarup BK",
    "dbuId": 1354
  },
  {
    "name": "Aasum IF",
    "dbuId": 1529
  }
];

const FRAME_SIZE   = 500;
const FRAME_GAP    = 40;
const ROW_GAP      = 80;
const LABEL_OFFSET = 90;

async function main() {
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });

  const nodes = [];
  let currentY = 0;

  // Group clubs by first letter (already sorted alphabetically)
  const groups = [];
  for (const club of clubs) {
    const letter = club.name[0].toUpperCase();
    if (!groups.length || groups[groups.length - 1].letter !== letter) {
      groups.push({ letter, clubs: [] });
    }
    groups[groups.length - 1].clubs.push(club);
  }

  for (const { letter, clubs: letterClubs } of groups) {
    // Letter label — sits to the left of the row, vertically centred
    const label = figma.createText();
    figma.currentPage.appendChild(label);
    label.characters = letter;
    label.fontSize   = 48;
    label.fontName   = { family: 'Inter', style: 'Bold' };
    label.fills      = [{ type: 'SOLID', color: { r: 0.7, g: 0.7, b: 0.7 } }];
    label.x          = -LABEL_OFFSET;
    label.y          = currentY + (FRAME_SIZE - label.height) / 2;
    nodes.push(label);

    // Frames for this letter — single row
    for (let i = 0; i < letterClubs.length; i++) {
      const { name, dbuId } = letterClubs[i];

      const frame = figma.createFrame();
      frame.name   = String(dbuId);
      frame.resize(FRAME_SIZE, FRAME_SIZE);
      frame.x      = i * (FRAME_SIZE + FRAME_GAP);
      frame.y      = currentY;
      frame.fills  = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
      frame.clipsContent = false;
      // No export settings — add manually in Figma when a badge is finished

      const text = figma.createText();
      frame.appendChild(text);
      text.characters          = name;
      text.fontSize            = 28;
      text.fontName            = { family: 'Inter', style: 'Regular' };
      text.textAlignHorizontal = 'CENTER';
      text.fills               = [{ type: 'SOLID', color: { r: 0.15, g: 0.15, b: 0.15 } }];
      text.resize(FRAME_SIZE - 64, text.height);
      text.x = 32;
      text.y = (FRAME_SIZE - text.height) / 2;

      nodes.push(frame);
    }

    currentY += FRAME_SIZE + ROW_GAP;
  }

  figma.currentPage.selection = nodes;
  figma.viewport.scrollAndZoomIntoView(nodes);
  figma.closePlugin('Done — ' + clubs.length + ' frames across ' + groups.length + ' letters.');
}

main();
